// One-shot: turn the two READMEs into data/plugins/*.yml (one file per entry).
//
// Run once, review the diff, commit. After this the READMEs are generated by
// scripts/generate-readme.mjs and must not be hand-edited.
import fs from 'node:fs'
import LOCALES from '../site/locales.mjs'
import { CAT_IDS, PLUGINS_DIR, slugFor, writeEntry } from './lib/entries.mjs'

// Same parse as build-site.mjs parseReadme(): heading match is a substring so
// the Chinese emoji prefixes are tolerated, and the entry URL is the join key.
function parseReadme(loc) {
  const out = new Map()
  let cat = null
  for (const line of fs.readFileSync(loc.readme, 'utf8').split(/\r?\n/)) {
    const h = line.match(/^#{2,3} (.+)$/)
    if (h) {
      cat = CAT_IDS.find((id) => h[1].includes(loc.categories[id])) ?? null
      continue
    }
    const m = line.match(/^- \[(.+?)\]\((https:\/\/github\.com\/[^)]+)\) ([—-]) (.+)$/)
    if (m && cat) out.set(m[2], { name: m[1], url: m[2], desc: m[4], cat })
  }
  return out
}

const [base, ...rest] = LOCALES.map((loc) => ({ loc, map: parseReadme(loc) }))
console.log(`${base.loc.readme}: ${base.map.size} entries`)

const problems = []
const entries = []
for (const [url, e] of base.map) {
  const description = { [base.loc.code]: e.desc }
  let ok = true
  for (const { loc, map } of rest) {
    const t = map.get(url)
    if (!t) {
      problems.push(`${loc.readme} missing: ${url}`)
      ok = false
      continue
    }
    if (t.cat !== e.cat) {
      problems.push(`${url}: category differs — ${base.loc.readme} says ${e.cat}, ${loc.readme} says ${t.cat}`)
      ok = false
    }
    description[loc.code] = t.desc
  }
  if (ok) entries.push({ url, name: e.name, category: e.cat, description })
}
for (const { loc, map } of rest) {
  for (const url of map.keys()) if (!base.map.has(url)) problems.push(`${loc.readme} has an entry missing from ${base.loc.readme}: ${url}`)
}

if (problems.length) {
  for (const p of problems) console.error(`  ${p}`)
  console.error(`\n${problems.length} problem(s) — refusing to migrate a broken pair of READMEs.`)
  process.exit(1)
}

// Slug collisions would silently drop an entry (two urls -> one filename).
const bySlug = new Map()
for (const e of entries) {
  const s = slugFor(e.url)
  if (bySlug.has(s)) {
    console.error(`slug collision "${s}": ${bySlug.get(s)} and ${e.url}`)
    process.exit(1)
  }
  bySlug.set(s, e.url)
}

fs.rmSync(PLUGINS_DIR, { recursive: true, force: true })
for (const e of entries) writeEntry(e)
console.log(`wrote ${entries.length} files to ${PLUGINS_DIR}/`)
